Update sample.integration.http.test.js
GoogleCloudPlatform/nodejs-docs-samples pull request #2311
Opened 2021-08-06 21:20 UTC by jenperson

Adding a function to cast the environment variable for `PORT` to an int.

Without `parseInt()`, when there is an environment variable set for `PORT`, the test fails because `process.env.PORT` is a string by default.

Test run on Node.js v12.14.1:
```
  1) functions_helloworld_http HTTP integration test
       "before all" hook for "helloHttp: should print a name":
     ValidationError: 'port' must be a number.
      at validateParameters (node_modules/wait-port/lib/validate-parameters.js:14:38)
      at /home/personjeh/Cloud/testing_gcf/http_integration/node_modules/wait-port/lib/wait-port.js:183:9
      at new Promise (<anonymous>)
      at waitPort (node_modules/wait-port/lib/wait-port.js:173:10)
      at Context.<anonymous> (test/sample_integration_test_http.js:22:11)
      at processImmediate (internal/timers.js:439:21)
```

2021-08-06 21:30 UTC, ace-n requested changes
LGTM, but this pattern is used in a bunch of other samples.

Would you mind updating those as well? (Try searching for `const PORT = process.env.PORT`)

2021-08-09 14:36 UTC, jenperson commented
I have updated all occurrences of `process.env.PORT` to explicitly cast to int.

2021-08-17 21:45 UTC, jenperson reviewed
All instances of `process.env.PORT` are now updated.

2021-08-17 22:08 UTC, ace-n approved these changes
Danke!

2021-08-30 17:35 UTC, sofisl approved these changes

2021-09-27 18:37 UTC, JustinBeckwith approved these changes

2022-02-09 21:20 UTC, tmatsuo commented
Justin's merge commit is making cla bot unhappy.

Maybe I can remove the commit and rebase.

2022-02-09 21:40 UTC, tmatsuo approved these changes

2022-02-09 21:40 UTC, merged