feat(appengine): added a new sample 'static-files-spa'
GoogleCloudPlatform/nodejs-docs-samples pull request #2360
Opened 2021-09-24 14:32 UTC by evil-shrike

The app demonstrates static files hosting in SPA scenarios.

Supposed to be used as a sample for new section in for https://cloud.google.com/appengine/docs/standard/nodejs/serving-static-files

2021-09-27 17:44 UTC, ace-n requested changes
LGTM other than a few nits.

I'm also going to clarify who should own this sample internally with my immediate team.

2021-09-27 17:44 UTC, ace-n commented on appengine/static-files-spa/app.js
> +// support of client-side routing in SPA apps (all routes that are not api lead to root)
Nit
```suggestion
// Support client-side routing in SPA apps (all routes that other than `/api` lead to root)
```

2021-09-27 17:44 UTC, ace-n commented on appengine/static-files-spa/public/index.html
> +
Nit: delete empty line.

2021-09-27 17:44 UTC, ace-n commented on appengine/static-files-spa/public/index.html
> +  function onNavigate(page) {
Nit: indent the contents of the `<script>...</script>` block by 2 more spaces.

2021-09-27 17:44 UTC, ace-n commented on appengine/static-files-spa/public/index.html
> +  <p>Mind the absence of page reloads on activating pages via the menu</p>
```suggestion
<p>Clicking links in the menu will <em>not</em>cause a page reload.</p>
```

2021-09-28 20:37 UTC, evil-shrike commented
@ace-n thanks, updated the code with your corrections

2022-01-27 19:27 UTC, dinagraves commented
Waiting for resolution on sample: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/6727#issuecomment-1023561960

2022-03-24 18:10 UTC, ace-n commented
The [companion Python PR](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/6727#issuecomment-1040602712) was closed, so I'm closing this one as well.

2022-03-24 18:10 UTC, closed without merging