chore: update CODEOWNERS for serverless samples
GoogleCloudPlatform/nodejs-docs-samples pull request #2718
Opened 2022-07-19 19:14 UTC by ace-n

@iennae @grayside please LGTM.

2022-07-19 19:17 UTC, iennae requested changes
Can we remove the individuals names from the list so that it's easier to manage overtime?

2022-07-19 19:21 UTC, ace-n commented
@iennae I'm not opposed to that, but if the `aap-dpes` team has a name change our team might be locked out.

(The Node.js repo maintainers could update that for us, though.)

2022-07-19 20:02 UTC, iennae approved these changes

2022-07-21 19:39 UTC, averikitsch approved these changes

2022-07-21 19:39 UTC, averikitsch commented
For the future update:
```
Unknown owner on line 20: make sure @ericschmidtatwork exists and has write access to the repository
functions/memorystore @ericschmidtatwork @GoogleCloudPlatform/nodejs-docs-samples-owners
Unknown owner on line 28: make sure @yoshi-nodejs exists and has write access to the repository
composer @leahecole @sofisl @yoshi-nodejs @GoogleCloudPlatform/nodejs-docs-samples-owners
Unknown owner on line 30: make sure @yuriatgoogle exists and has write access to the repository
monitoring/opencensus @yuriatgoogle @GoogleCloudPlatform/nodejs-docs-samples-owners
```

2022-08-02 20:38 UTC, sofisl approved these changes

2022-08-02 20:38 UTC, merged