docs(demosite-recaptcha): add demosite v1
GoogleCloudPlatform/nodejs-docs-samples pull request #3025
Opened 2023-02-09 17:43 UTC by Sita04

# Description
This Pull Request merges the v1 version of Demosite code. It provides information on setting up a webapp to demonstrate reCAPTCHA score key integration in a gamified environment.

To test, kindly run the Docker-compose file.

For more context, see: [go/recaptcha-enterprise-demosite-prd](https://goto.google.com/recaptcha-enterprise-demosite-prd)

### Note
DO NOT delete the branch post-merge.

2023-02-09 23:59 UTC, kweinmeister approved these changes

2023-02-10 09:34 UTC, rsamborski requested changes
Please add a README.md similar to the one in Python. Also are you planning to add any tests?

2023-02-13 15:59 UTC, bcoe approved these changes

2023-02-21 16:54 UTC, Sita04 commented
@rsamborski I have updated the README file with minimal information as it's under discussion if deployment outside console should be permitted.
Tests: Unit tests will be added in the upcoming commits.

2023-02-21 17:10 UTC, rsamborski approved these changes

2023-02-21 18:41 UTC, merged

2023-02-21 18:42 UTC, Sita04 commented
DO NOT Delete the branch. It's used for demosite collboration.