Fetch acl sample code for content warehouse
GoogleCloudPlatform/nodejs-docs-samples pull request #3287
Opened 2023-06-21 11:19 UTC by paulinawins

## Description
Fixes issue

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed guidelines from [CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md) and [Samples Style Guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [x] **Tests** pass:   `npm test` (see [Testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#run-the-tests-for-a-single-sample))
- [x] **Lint** pass:   `npm run lint` (see [Style](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#style))
- [x] These samples need a new **API enabled** in testing projects to pass (let us know which ones). content-warehouse API
- [x] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CODEOWNERS) with the codeowners for this sample
- [x] This sample adds a new sample directory, and I created [GitHub Actions workflow](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#adding-new-samples) for this sample
- [x] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

2023-06-21 11:24 UTC, paulinawins commented
Hi @telpirion or @holtskinner, could either of you review this PR (adds a nodeJS sample code for document warehouse)?

2023-06-21 14:09 UTC, kweinmeister commented on .github/blunderbuss.yml
> +    - GoogleCloudPlatform/document-ai-samples-contributors
Nit: keep final new line

2023-06-21 14:10 UTC, kweinmeister commented on CODEOWNERS
> +document-warehouse @GoogleCloudPlatform/dee-data-ai @GoogleCloudPlatform/nodejs-samples-reviewers
Can we also include `document-ai-samples-contributors` here? Can be handled in another PR if you'd like.

2023-06-21 14:11 UTC, kweinmeister commented on document-warehouse/test/fetch-acl.test.js
> +//TODO: Create a PR for this! :)
Remove this comment?

2023-06-21 14:13 UTC, kweinmeister requested changes
Looks good, but minor changes requested. Thank you!

2023-06-21 14:31 UTC, kweinmeister commented
Also if you can address these header check issues that would be great. The conventional commit check is not required, and not critical to me to change at this point (but other Node reviewers please feel free to assert this).

```
document-warehouse/.eslintrc.yml is missing a valid license header.
document-warehouse/test/.eslintrc.yml is missing a valid license header.
document-warehouse/test/fetch-acl.test.js is missing a valid copyright line.
```

2023-06-21 17:19 UTC, paulinawins commented on document-warehouse/test/.eslintrc.yml
> +---
One is intended only for the tests in this directory and the other is for the sample code

2023-06-21 19:03 UTC, paulinawins reviewed
Addressed all of these requests

2023-06-21 19:04 UTC, paulinawins reviewed
marking conversations as resolved

2023-06-23 23:02 UTC, kweinmeister approved these changes

2023-06-23 23:52 UTC, pattishin approved these changes

2023-06-24 01:56 UTC, merged