feat(cloud-sql): add tedious connector sample
GoogleCloudPlatform/nodejs-docs-samples pull request #3333
Opened 2023-07-10 22:18 UTC by ruyadorno

This new sample uses the Cloud SQL Node.js Connector to connect to Cloud SQL instances instead of relying on the standalone Cloud SQL Proxy.

The original SQL Server sample from `cloud-sql/sqlserver/mssql` does not support the Cloud SQL Node.js Connector so this PR adds a new example residing in a new location: `cloud-sql/sqlserver/tedious`.

Ref: https://github.com/GoogleCloudPlatform/cloud-sql-nodejs-connector
Ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3264
Ref: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3266

2023-07-11 13:30 UTC, jackwotherspoon requested changes
made a first pass with a few small comments

2023-07-11 13:30 UTC, jackwotherspoon commented on cloud-sql/sqlserver/tedious/connect-tcp.js
> +// connectWithTcpSocket initializes a TCP connection pool for a Cloud SQL
nit: connection pooling mentioned here also

2023-07-11 13:30 UTC, jackwotherspoon commented on cloud-sql/sqlserver/tedious/README.md
> +    gcloud app deploy app.flexible.yaml
same here is `app.flexible.yaml` missing by mistake?

2023-07-11 14:48 UTC, jackwotherspoon reviewed
LGTM,  couple more minor README nits

2023-07-11 14:48 UTC, jackwotherspoon commented on cloud-sql/sqlserver/tedious/README.md
> +to pass the environment variables into the runtime.
See below comment, might need to showcase updated yaml as Proxy yaml differs https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/cloud-sql/sqlserver/mssql/app.standard.yaml

2023-07-11 20:13 UTC, ruyadorno commented on cloud-sql/sqlserver/tedious/README.md
> +instructions](https://cloud.google.com/sql/docs/sqlserver/sql-proxy#install) as an
sounds to me like it's simpler to fix the README example rn with the correct instructions for v2 and then follow up with a PR to fix it in the other samples later

2023-07-11 20:29 UTC, enocom commented on cloud-sql/sqlserver/tedious/README.md
> +instructions](https://cloud.google.com/sql/docs/sqlserver/sql-proxy#install) as an
+1 Sounds good to me @ruyadorno. Thanks for catching this.

2023-07-11 20:29 UTC, jackwotherspoon commented on cloud-sql/sqlserver/tedious/README.md
> +instructions](https://cloud.google.com/sql/docs/sqlserver/sql-proxy#install) as an
I already updated the Python doc samples READMEs to use v2 so you could use this commit as ref: https://github.com/GoogleCloudPlatform/python-docs-samples/commit/9606fc25cc8a13d28a526066a01a95024ec0e970

2023-07-12 13:52 UTC, jackwotherspoon requested changes
Final two comments I promise, otherwise LGTM

2023-07-12 13:52 UTC, jackwotherspoon commented on cloud-sql/sqlserver/tedious/README.md
> +  INSTANCE_HOST: 172.17.0.1
that IP address is only for GAE flexible I believe, normal localhost IP should work for GAE standard
```suggestion
  INSTANCE_HOST: 127.0.0.1
```

2023-07-12 13:52 UTC, jackwotherspoon commented on cloud-sql/sqlserver/tedious/README.md
> +  name: projects/<MY-PROJECT>/locations/<INSTANCE-REGION>/connectors/<CONNECTOR-NAME>
don't think we need the VPC access connector for the default usage.

2023-07-12 14:53 UTC, jackwotherspoon approved these changes
LGTM

2023-07-12 14:53 UTC, merged