Delete schema
GoogleCloudPlatform/nodejs-docs-samples pull request #3375
Opened 2023-08-01 18:13 UTC by paulinawins

## Description

Fixes #issue

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed guidelines from [CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md) and [Samples Style Guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [x] **Tests** pass:   `npm test` (see [Testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#run-the-tests-for-a-single-sample))
- [x] **Lint** pass:   `npm run lint` (see [Style](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#style))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This pull request is from a branch created directly off of `GoogleCloudPlatform/nodejs-docs-samples`. Not a fork.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new sample directory, and I created [GitHub Actions workflow](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#adding-new-samples) for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

2023-08-01 18:29 UTC, holtskinner commented
Add a test for this function. Similar to what was done in https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3292

2023-08-02 16:35 UTC, telpirion requested changes
This sample requires an integration test:
https://googlecloudplatform.github.io/samples-style-guide/#testing

There are some stylistic differences in this sample from the norm. I suggest that you look at  the following examples:

+ [Sample](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/speech/adaptationInlinePhraseSet.v2.js)
+ [Test](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/speech/system-test/adaptationInlinePhraseSet.v2.test.js)

2023-08-02 16:35 UTC, telpirion commented on document-warehouse/delete-document-schema.js
> +    console.log(request);
Remove or print a more meaningful message to stdout.

2023-08-02 16:35 UTC, telpirion commented on document-warehouse/delete-document-schema.js
> +    const response = serviceClient.deleteDocumentSchema(request);
Use `await` here.

2023-08-02 16:35 UTC, telpirion commented on document-warehouse/delete-document-schema.js
> +    response.then(
We typically use `await` to force a method call to become blocking. Remove the `then()` call here.

2023-08-02 16:35 UTC, telpirion commented on document-warehouse/delete-document-schema.js
> +      error => console.log(`Failed!\n${error}`)
Remove "Success!" and "Failure!" characters from messages.

2023-08-02 16:35 UTC, telpirion commented on document-warehouse/delete-document-schema.js
> +main(...process.argv.slice(2)).catch(err => {
Remove CLI setup:
https://googlecloudplatform.github.io/samples-style-guide/#no-cli

Instead, export the main method as `deleteDocumentSchema`.

2023-08-12 20:57 UTC, paulinawins reviewed
Done. Please review and approve when you have the time. 
@telpirion

2023-08-14 19:16 UTC, closed without merging