Fix tests for document-warehouse directory
GoogleCloudPlatform/nodejs-docs-samples pull request #3471
Opened 2023-08-21 20:48 UTC by paulinawins

## Description

## Checklist
- [ x ] I have followed guidelines from [CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md) and [Samples Style Guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ x ] **Tests** pass:   `npm test` (see [Testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#run-the-tests-for-a-single-sample))
- [ x ] **Lint** pass:   `npm run lint` (see [Style](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#style))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ x ] This pull request is from a branch created directly off of `GoogleCloudPlatform/nodejs-docs-samples`. Not a fork.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new sample directory, and I created [GitHub Actions workflow](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#adding-new-samples) for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ x ] Please **merge** this PR for me once it is approved

2023-08-22 14:26 UTC, holtskinner requested changes
Be sure that the tests pass

2023-08-22 14:26 UTC, holtskinner commented on document-warehouse/test/set-acl.test.js
> +  }
It might make sense to put all acl tests in the same file so they can all use this function

2023-08-22 14:26 UTC, holtskinner commented on document-warehouse/set-acl.js
> -      request.requestMetadata = {userInfo: {id: userId}};
Any reason this was removed?

2023-09-07 16:51 UTC, paulinawins reviewed
Deleted all of the code for now to upblock this directory and will add them when the DocAI warehouse instance is updated (b/298437827). Could I get approvals to remove both of the ACL sample and test code with this PR?

2023-09-07 16:53 UTC, paulinawins commented
> Be sure that the tests pass

@holtskinner Is there any way I could get this PR to pass and merged with the removal of code for this directory?

2023-09-10 03:23 UTC, closed without merging