wip: convert CI testing to use Makefile actions
GoogleCloudPlatform/nodejs-docs-samples pull request #3579
Opened 2023-11-29 20:13 UTC by muncus

2023-12-21 02:21 UTC, pattishin requested changes
Ty Marc! Added small suggestions for GCP project environment.

2023-12-21 02:21 UTC, pattishin commented on .github/workflows/ai-platform-snippets.yaml
> +        GOOGLE_SAMPLES_PROJECT: "nodejs-docs-samples-tests"
```suggestion
        GOOGLE_SAMPLES_PROJECT: "long-door-651"
```

2023-12-21 02:21 UTC, pattishin commented on .github/workflows/dialogflow-cx.yaml
> +        GOOGLE_SAMPLES_PROJECT: "nodejs-docs-samples-tests"
```suggestion
         GOOGLE_SAMPLES_PROJECT: "long-door-651"
```

2023-12-21 02:21 UTC, pattishin commented on .github/workflows/functions-slack.yaml
> +        GOOGLE_SAMPLES_PROJECT: "nodejs-docs-samples-tests"
```suggestion
        GOOGLE_SAMPLES_PROJECT: "long-door-651"
```

2023-12-21 02:21 UTC, pattishin commented on .github/workflows/utils/ci-secrets.yaml.njk
> +        GOOGLE_SAMPLES_PROJECT: "nodejs-docs-samples-tests"
```suggestion
        GOOGLE_SAMPLES_PROJECT: "long-door-651"
```

2024-01-02 16:26 UTC, holtskinner approved these changes

2024-01-24 05:20 UTC, pattishin approved these changes
👍🏼 ty!

2024-01-24 05:20 UTC, merged