feat: batch_create_persistent_job
GoogleCloudPlatform/nodejs-docs-samples pull request #3778
Opened 2024-08-06 13:13 UTC by gryczj

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed guidelines from [CONTRIBUTING.MD](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md) and [Samples Style Guide](https://googlecloudplatform.github.io/samples-style-guide/)
- [ ] **Tests** pass:   `npm test` (see [Testing](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#run-the-tests-for-a-single-sample))
- [ ] **Lint** pass:   `npm run lint` (see [Style](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#style))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This pull request is from a branch created directly off of `GoogleCloudPlatform/nodejs-docs-samples`. Not a fork.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new sample directory, and I created [GitHub Actions workflow](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/CONTRIBUTING.md#adding-new-samples) for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2024-08-08 18:17 UTC, subfuzion requested changes
Hi @gryczj Looks good, just one requested change, please. Thanks!

2024-08-08 18:17 UTC, subfuzion commented on batch/create/create_persistent_disk_job.js
> +});
Acknowledging that some inconsistency currently exists in our samples, please remove this. It doesn't add value to the sample; an unhandled rejection will terminate the process and set the exitCode and provide a full stack trace. If it's important to handle, then using `try-catch` blocks (or [Promise.prototype.catch()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch)), is more appropriate.

2024-08-08 20:15 UTC, subfuzion requested changes

2024-08-08 20:15 UTC, subfuzion commented on batch/create/create_persistent_disk_job.js
> +main();
Promise returned from main is ignored. You can address both this and the previous comment I made by make the following change:

```javascript
main().catch(err => {
  console.error(err);
  process.exitCode = 1;
});
```

2024-08-09 07:34 UTC, gryczj commented
@subfuzion fixed :)

2024-08-09 23:07 UTC, subfuzion approved these changes

2024-08-09 23:16 UTC, merged